version: 2.1
orbs:
  cypress: cypress/cypress@dev:0.0.1
workflows:
  build:
    jobs:
      # record Cypress tests on the Dashboard
      - cypress/run:
          group: "all tests"
          record: true
